name: Deploy React App to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automated deployment to GitHub Pages"
        git push origin HEAD:gh-pages --force
